export { haWebSocket, HAWebSocketService } from './haWebSocket'
export { presenceService, PresenceService } from './presenceService'
export { spotifyService, SpotifyService } from './spotifyService'
export { oasisService, OasisService } from './oasisService'
export { photoFrameService, PhotoFrameService } from './photoFrameService'
export { nfcService, NFCService, isNFCSupported, isWebNFCSupported, isCapacitorNative, getNFCStatus } from './nfcService'
export * from './types'
