# Concord Smart Office - Staff Presence System Package

# Input helpers for tracking staff presence
input_boolean:
  # Add staff members here, e.g.:
  # staff_john_present:
  #   name: "John - Present"
  #   icon: mdi:account

input_datetime:
  # Track arrival times, e.g.:
  # staff_john_arrival:
  #   name: "John - Arrival Time"
  #   has_date: true
  #   has_time: true

# Template sensors for presence overview
template:
  - sensor:
      - name: "Staff Currently Present"
        state: >
          {{ states.input_boolean
             | selectattr('entity_id', 'match', 'input_boolean.staff_.*_present')
             | selectattr('state', 'eq', 'on')
             | list | count }}
        attributes:
          staff_list: >
            {{ states.input_boolean
               | selectattr('entity_id', 'match', 'input_boolean.staff_.*_present')
               | selectattr('state', 'eq', 'on')
               | map(attribute='name')
               | list }}

# Automations for presence management
automation:
  - id: presence_scan_in_webhook
    alias: "Presence - Handle Scan In"
    description: "Process scan-in events from QR/NFC"
    trigger:
      - platform: webhook
        webhook_id: staff_scan_in
        local_only: false
    action:
      - service: input_boolean.turn_on
        target:
          entity_id: "input_boolean.staff_{{ trigger.json.staff_id }}_present"
      - service: input_datetime.set_datetime
        target:
          entity_id: "input_datetime.staff_{{ trigger.json.staff_id }}_arrival"
        data:
          datetime: "{{ now().isoformat() }}"
      - event: staff_scanned_in
        event_data:
          staff_id: "{{ trigger.json.staff_id }}"
          method: "{{ trigger.json.method }}"

  - id: presence_scan_out_webhook
    alias: "Presence - Handle Scan Out"
    description: "Process scan-out events from QR/NFC"
    trigger:
      - platform: webhook
        webhook_id: staff_scan_out
        local_only: false
    action:
      - service: input_boolean.turn_off
        target:
          entity_id: "input_boolean.staff_{{ trigger.json.staff_id }}_present"
      - event: staff_scanned_out
        event_data:
          staff_id: "{{ trigger.json.staff_id }}"
          method: "{{ trigger.json.method }}"

# Scripts for presence operations
script:
  scan_in_staff:
    alias: "Scan In Staff Member"
    fields:
      staff_id:
        description: "Staff member identifier"
        example: "john"
      method:
        description: "Scan method (qr, nfc)"
        example: "qr"
    sequence:
      - service: input_boolean.turn_on
        target:
          entity_id: "input_boolean.staff_{{ staff_id }}_present"
      - service: input_datetime.set_datetime
        target:
          entity_id: "input_datetime.staff_{{ staff_id }}_arrival"
        data:
          datetime: "{{ now().isoformat() }}"

  scan_out_staff:
    alias: "Scan Out Staff Member"
    fields:
      staff_id:
        description: "Staff member identifier"
        example: "john"
    sequence:
      - service: input_boolean.turn_off
        target:
          entity_id: "input_boolean.staff_{{ staff_id }}_present"
